# Generated by Django 2.2.16 on 2021-03-28 17:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_role', models.CharField(choices=[('ADMINISTRATOR', 'ADMINISTRATOR'), ('USER', 'USER')], default='USER', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('email_confirmed', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=255)),
                ('middle_name', models.CharField(default='', max_length=255)),
                ('last_name', models.CharField(default='', max_length=255)),
                ('nickname', models.CharField(blank=True, default='', max_length=255)),
                ('avatar', models.ImageField(blank=True, default='user_avatars/default_avatar.png', upload_to='user_avatars')),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHER', 'OTHER'), ('NOT_SPECIFIED', 'NOT_SPECIFIED')], default='NOT_SPECIFIED', max_length=255)),
                ('date_of_birth', models.DateField(default=datetime.date(2000, 1, 1))),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_for_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(blank=True, default='', max_length=255)),
                ('preference', models.CharField(blank=True, default='', max_length=255)),
                ('last_modified_utc', models.DateTimeField(auto_now=True, null=True)),
                ('created_on_utc', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=255)),
                ('used', models.BooleanField(default=False)),
                ('last_modified_utc', models.DateTimeField(auto_now=True, null=True)),
                ('created_on_utc', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailConfirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_sent_on_datetime_utc', models.DateTimeField(blank=True, default=None, editable=False, null=True)),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('used', models.BooleanField(default=False)),
                ('last_modified_utc', models.DateTimeField(auto_now=True, null=True)),
                ('created_on_utc', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('from_email', models.CharField(default='', max_length=255)),
                ('to_email', models.CharField(default='', max_length=255)),
                ('used', models.BooleanField(default=False)),
                ('last_modified_utc', models.DateTimeField(auto_now=True, null=True)),
                ('created_on_utc', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
