# Generated by Django 2.2.16 on 2021-05-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20210412_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='personal_website',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
