# Generated by Django 2.2.16 on 2021-05-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_userprofile_personal_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='user_ratings_json',
            field=models.TextField(default='{}'),
        ),
    ]
