# Generated by Django 2.2.16 on 2021-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_userpreference_user_ratings_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='user_ratings_json',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_ratings_json',
            field=models.TextField(default='{}'),
        ),
    ]
