# Generated by Django 2.2.16 on 2021-05-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20210506_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='assigned_CategoryItems_JSON',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
