# Generated by Django 4.0.3 on 2022-03-17 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_userprofile_total_performance_percentage_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailconfirmation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='passwordreset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='assigned_CategoryItems_JSON',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_performance_percentage_string',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_ratings_json',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='EmailChange',
        ),
        migrations.DeleteModel(
            name='EmailConfirmation',
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
        migrations.DeleteModel(
            name='UserPreference',
        ),
    ]
