# Generated by Django 4.0.3 on 2022-03-20 10:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0008_remove_emailconfirmation_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='primary_rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rm_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator user'), ('USER', 'Default user'), ('CLIENT', 'Client user')], default='USER', max_length=255),
        ),
    ]
