# Generated by Django 4.0.3 on 2022-03-20 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0009_userprofile_primary_rm_alter_user_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='primary_rm',
        ),
        migrations.AddField(
            model_name='user',
            name='primary_rm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rm_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
