# Generated by Django 4.0.3 on 2022-03-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_remove_userprofile_primary_rm_user_primary_rm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_on',
        ),
        migrations.AddField(
            model_name='user',
            name='created_on_utc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_modified_utc',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_on_utc',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_modified_utc',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
