# Generated by Django 4.0.3 on 2022-03-25 18:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_utc', models.DateTimeField(auto_now_add=True)),
                ('last_modified_utc', models.DateTimeField(auto_now=True)),
                ('subject', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipient_user', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sender_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on_utc', models.DateTimeField(auto_now_add=True)),
                ('last_modified_utc', models.DateTimeField(auto_now=True)),
                ('custom_name', models.CharField(blank=True, default='', max_length=255)),
                ('document', models.FileField(blank=True, default='DEFAULT/_placeholder.txt', upload_to='documents/%Y/%m/%d/')),
                ('document_type', models.CharField(choices=[('OFFICIAL', 'Official document'), ('FINANCIAL', 'Financial document'), ('UNDEFINED_DOCUMENT_TYPE', 'Undefined document type')], default='UNDEFINED_DOCUMENT_TYPE', max_length=255)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.email')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
