# Generated by Django 4.0.3 on 2022-03-17 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('url', models.CharField(blank=True, default='', max_length=255)),
                ('created_on_utc', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_utc', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_client_user', to=settings.AUTH_USER_MODEL)),
                ('rm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_rm_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summery', models.TextField(blank=True, default='')),
                ('body', models.TextField(blank=True, default='')),
                ('uuid', models.CharField(default=uuid.uuid4, max_length=255)),
                ('created_on_utc', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_modified_utc', models.DateTimeField(auto_now=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_client_user', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.document')),
                ('rm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_rm_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
