# Generated by Django 4.0.3 on 2022-03-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='summery',
            new_name='subject',
        ),
        migrations.RemoveField(
            model_name='email',
            name='document',
        ),
        migrations.AddField(
            model_name='document',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_client_user', to='Main.email'),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.CharField(choices=[('RM', 'Relational Manager'), ('CLIENT', 'Client')], default='CLIENT', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doc_uploaded_by_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='email',
            name='reciever_email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='email',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_sender_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
