# Generated by Django 4.0.3 on 2022-03-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_alter_document_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.email'),
        ),
    ]
