# Generated by Django 4.0.3 on 2022-03-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_rename_summery_email_subject_remove_email_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/'),
        ),
    ]
